import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("UI only exposes stage-appropriate controls", async () => {
  const [html, css, appJs, exportsJs, setupJs, summariesJs, transcriptDrawerJs, utilsJs, design] = await Promise.all([
    readFile(new URL("../src/ui/index.html", import.meta.url), "utf8"),
    readFile(new URL("../src/ui/styles.css", import.meta.url), "utf8"),
    readFile(new URL("../src/ui/app.mjs", import.meta.url), "utf8"),
    readFile(new URL("../src/ui/documentExports.mjs", import.meta.url), "utf8"),
    readFile(new URL("../src/ui/setupController.mjs", import.meta.url), "utf8"),
    readFile(new URL("../src/ui/meetingSummaries.mjs", import.meta.url), "utf8"),
    readFile(new URL("../src/ui/transcriptDrawer.mjs", import.meta.url), "utf8"),
    readFile(new URL("../src/ui/uiUtils.mjs", import.meta.url), "utf8"),
    readFile(new URL("../DESIGN.md", import.meta.url), "utf8")
  ]);
  const js = `${appJs}\n${exportsJs}\n${setupJs}\n${summariesJs}\n${transcriptDrawerJs}\n${utilsJs}`;

  assert.match(design, /three-stage desktop utility/);
  assert.match(design, /Setup/);
  assert.match(design, /Listening/);
  assert.match(design, /Review/);
  assert.match(design, /Traditional Chinese/);
  assert.match(design, /AI suggestion must be dismissible/);

  assert.match(html, /body data-state="setup"/);
  assert.match(html, /setup-screen/);
  assert.match(html, /setupDropZone/);
  assert.match(html, /setupContext/);
  assert.match(html, /provider-settings/);
  assert.match(html, /textProviderName/);
  assert.match(html, /textProviderChoice/);
  assert.match(html, /liveTextProviderChoice/);
  assert.match(html, /claude-code-oauth/);
  assert.match(html, /loginTextProvider/);
  assert.match(html, /enableOAuthProvider/);
  assert.match(html, /AI 狀態/);
  assert.match(html, /sttProfileChoice/);
  assert.match(html, /語音轉文字/);
  assert.match(html, /value="whisper-standard"/);
  assert.doesNotMatch(html, /value="system-speech"/);
  assert.match(html, /setupAudioReadiness/);
  assert.match(html, /setupAudioPermissions/);
  assert.match(html, /開啟螢幕與系統錄音/);
  assert.match(html, /會前/);
  assert.match(html, /背景/);
  assert.match(html, /檔案/);
  assert.doesNotMatch(html, /檢查登入/);
  assert.match(html, /prepDictation/);
  assert.match(html, /droppedFileCount/);
  assert.match(html, /prepSummary/);
  assert.match(html, /AI 重點整理/);
  assert.match(html, /listening-curtain/);
  assert.match(html, /review-screen/);
  assert.match(html, /reviewStatus/);
  assert.match(html, /會議結束後會在這裡整理文件/);
  assert.match(html, /postMeetingSummary/);
  assert.match(html, /postMeetingTranscript/);
  assert.match(html, /data-download-format="summary-json"/);
  assert.match(html, /data-download-format="summary-markdown"/);
  assert.match(html, /data-download-format="summary-pdf"/);
  assert.match(html, /data-download-format="transcript-json"/);
  assert.match(html, /data-download-format="transcript-txt"/);
  assert.match(html, /data-download-format="transcript-pdf"/);
  assert.match(html, /downloadErrorLog/);
  assert.match(html, /錯誤紀錄 JSON/);
  assert.match(html, /AI 整理/);
  assert.match(html, /逐字稿/);
  assert.match(html, /value="mixed">麥克風 \+ 系統音訊/);
  assert.match(html, /curtainOpacity/);
  assert.match(html, /min="10"/);
  assert.match(html, /max="100"/);
  assert.match(html, /value="100"/);
  assert.match(html, /startListening[^>]+disabled/);
  assert.match(html, /transcript-drawer/);
  assert.match(html, /transcriptDrawerToggle/);
  assert.match(html, /transcriptPreview/);
  assert.match(html, /transcriptFull/);
  assert.match(html, /openAudioPermissions/);
  assert.match(html, /開啟權限設定/);
  assert.match(html, /逐字稿/);
  assert.match(html, /目前沒有提醒/);
  assert.match(html, /0 句/);
  assert.match(html, /最近對話會顯示在這裡/);
  assert.match(html, /stopListening[^>]+>結束會議</);
  assert.doesNotMatch(html, /目前聽到的重點/);
  assert.doesNotMatch(html, /Popover 預覽/);
  assert.doesNotMatch(html, /手動逐字稿/);
  assert.doesNotMatch(html, /Native STT/);
  assert.doesNotMatch(html, />Pre-flight</i);
  assert.doesNotMatch(html, />Context</i);
  assert.doesNotMatch(html, />Files</i);
  assert.doesNotMatch(html, />AI Brief</i);
  assert.doesNotMatch(html, />Review</i);
  assert.doesNotMatch(html, />Document/);
  assert.doesNotMatch(html, />Export</i);

  assert.match(css, /body\[data-state="listening"\] \.setup-screen,[\s\S]*body\[data-state="review"\] \.listening-curtain\s*\{\s*display: none;/);
  assert.match(css, /body\[data-state="listening"\] \.listening-curtain,[\s\S]*body\[data-state="review"\] \.review-screen\s*\{\s*display: grid;/);
  assert.match(css, /\[hidden\]\s*\{\s*display: none !important;/);
  assert.match(css, /backdrop-filter: blur/);
  assert.match(css, /--curtain-alpha: 1/);
  assert.match(css, /--glass: rgba\(16, 18, 20, var\(--curtain-alpha\)\)/);
  assert.match(css, /body\[data-state="listening"\] \.shell\s*\{\s*background: transparent;/);
  assert.match(css, /\.transcript-drawer/);
  assert.match(css, /\.transcript-preview/);
  assert.match(css, /\.transcript-full/);
  assert.match(css, /\.transcript-group/);
  assert.match(css, /\.transcript-count/);
  assert.match(css, /\.transcript-line\.partial/);
  assert.match(css, /max-height: 34vh/);
  assert.match(css, /\.listening-status/);
  assert.match(css, /\.permission-action/);
  assert.match(css, /\.setup-audio-readiness/);
  assert.match(css, /\.stt-settings/);
  assert.match(css, /\.stt-settings\.warning/);
  assert.match(css, /\.status-dot\.warning/);
  assert.match(css, /\.state-label::before/);
  assert.match(css, /\.prep-layout/);
  assert.match(css, /\.context-dropzone/);
  assert.match(css, /\.primary-export/);
  assert.match(css, /\.secondary-export/);
  assert.match(css, /\.evidence-disclosure/);
  assert.match(css, /\.review-status/);
  assert.match(css, /\.processing-block/);
  assert.match(css, /@keyframes processing-sweep/);

  assert.match(js, /initializeSetupState\(\)/);
  assert.match(js, /refreshPlatformShellPlan/);
  assert.match(js, /applyPlatformCaptureAvailability/);
  assert.match(js, /option\[value="mixed"\]/);
  assert.match(js, /refreshTextProviderStatus/);
  assert.match(js, /scheduleTextProviderRefresh/);
  assert.match(js, /textProviderRefreshTimers/);
  assert.match(js, /clearTimeout\(timer\)/);
  assert.match(js, /text_provider_status/);
  assert.match(js, /forceRefresh/);
  assert.match(js, /open_text_provider_install_guide/);
  assert.match(html, /openTextProviderInstallGuide/);
  assert.match(html, /copyTextProviderInstallCommand/);
  assert.match(html, /refreshTextProviderStatus/);
  assert.match(html, /AI 連接器|連接器/);
  assert.match(js, /npm install -g @openai\/codex/);
  assert.match(js, /npm install -g @anthropic-ai\/claude-code/);
  assert.match(js, /start_text_provider_login/);
  assert.match(js, /set_session_text_provider/);
  assert.match(js, /TEXT_PROVIDER_STORAGE_KEY/);
  assert.match(js, /LOCAL_STT_PROFILE_STORAGE_KEY/);
  assert.match(js, /refreshLocalSttStatus/);
  assert.match(js, /set_local_stt_profile_command/);
  assert.match(js, /download_local_stt_model_command/);
  assert.match(js, /local_stt_model_download_progress/);
  assert.match(html, /downloadSttModel/);
  assert.match(css, /\.stt-download-progress/);
  assert.match(js, /local_stt_status_command/);
  assert.match(js, /canStartWithSelectedStt/);
  assert.match(js, /meeting\.start_blocked_without_stt/);
  assert.match(js, /localWhisperEngineMissing/);
  assert.match(js, /Whisper 尚未就緒/);
  assert.match(js, /selectedTextProviderId/);
  assert.match(js, /claude-code-oauth/);
  assert.match(js, /generate_ai_summary_oauth/);
  assert.match(js, /generate_prep_summary_oauth/);
  assert.match(js, /schedulePrepSummaryGeneration/);
  assert.match(js, /generatePrepSummary/);
  assert.match(js, /clearTimeout\(prepSummaryTimer\)/);
  assert.match(js, /prepSummaryRequestId \+= 1/);
  assert.match(js, /if \(requestId !== prepSummaryRequestId\) return/);
  assert.match(js, /請先登入並啟用 AI/);
  assert.match(js, /extract_live_state_patch_oauth/);
  assert.match(js, /maybeRunLiveAiExtraction/);
  assert.match(js, /liveAiPipelineState = \{ \.\.\.liveAiPipelineState, running: true \}/);
  assert.match(js, /LIVE_AI_POLICY/);
  assert.match(js, /shouldTriggerLiveAiForEvent/);
  assert.match(js, /scheduleLiveAiExtractionForEvent\(payload\.event\)/);
  assert.match(js, /revise_transcript_oauth/);
  assert.match(js, /scheduleLiveTranscriptRevision/);
  assert.match(js, /const LIVE_TRANSCRIPT_REVISION_DURING_CAPTURE_ENABLED = false/);
  assert.match(js, /function scheduleLiveTranscriptRevision\(\) \{\s*if \(!LIVE_TRANSCRIPT_REVISION_DURING_CAPTURE_ENABLED\) return;/);
  assert.match(js, /TRANSCRIPT_REVISION_CONTEXT_WINDOW_SIZE/);
  assert.match(js, /TRANSCRIPT_REVISION_EDITABLE_WINDOW_SIZE/);
  assert.match(js, /TRANSCRIPT_REVISION_MIN_NEW_EVENTS/);
  assert.match(js, /TRANSCRIPT_REVISION_STABLE_AFTER_REVISIONS/);
  assert.match(js, /buildTranscriptRevisionSnapshot/);
  assert.match(js, /lastTranscriptRevisionEventCount = revisionSnapshot\.endCount/);
  assert.match(js, /lastTranscriptRevisionAt = Date\.now\(\)/);
  assert.match(js, /await maybeRunLiveTranscriptRevision\(\{ allowReview: true, force: true \}\)/);
  assert.doesNotMatch(js, /lastTranscriptRevisionEventCount = transcriptEvents\.length/);
  assert.match(js, /displayedTranscriptEvents/);
  assert.match(js, /editableStartIndex/);
  assert.match(js, /refreshTranscriptRevisionStability/);
  assert.match(js, /groupTranscriptLines/);
  assert.match(js, /aiActivityMessages/);
  assert.match(js, /setAiActivity/);
  assert.match(js, /clearAiActivity/);
  assert.match(js, /對方 A|未標記來源/);
  assert.match(js, /markLiveAiFailure/);
  assert.match(js, /suspendedUntilMs/);
  assert.doesNotMatch(js, /lastAiExtractionEventCount/);
  assert.match(js, /AI 正在盯對方發言/);
  assert.match(js, /oauthAiEnabled/);
  assert.doesNotMatch(js, /AI_ENABLED_STORAGE_KEY/);
  assert.doesNotMatch(js, /readAiEnabledPreference/);
  assert.match(js, /setAiEnabledPreference\(true\)/);
  assert.doesNotMatch(js, /authenticated && !oauthAiEnabled[\s\S]*setAiEnabledPreference\(true\)/);
  assert.match(js, /window\.localStorage\?\.setItem/);
  assert.match(js, /canStartWithAi/);
  assert.match(js, /updateStartButtonCopy/);
  assert.match(js, /開始記錄會議音訊/);
  assert.match(js, /請先按左側啟用 AI/);
  assert.match(js, /providerStartBlockedCopy/);
  assert.match(js, /請先安裝 \$\{selectedTextProviderLabel\(\)\}/);
  assert.match(js, /textProviderEnabled: canStartWithAi\(\)/);
  assert.match(js, /textProviderId: selectedTextProviderId/);
  assert.match(js, /document\.body\.dataset\.state === "listening"/);
  assert.doesNotMatch(js, /ai\.set_session_text_provider[\s\S]{0,260}setAiEnabledPreference\(false\)/);
  assert.match(js, /if \(nextProviderId !== selectedTextProviderId\) return/);
  assert.match(js, /syncStartButtonAvailability/);
  assert.match(js, /請先啟用 AI/);
  assert.match(js, /啟用本場/);
  assert.match(js, /connectorInstalled/);
  assert.match(js, /Meeting Copilot 不會保存 CLI token/);
  assert.match(js, /selectedTextProviderLabel\(\)\} 已啟用/);
  assert.match(js, /installOpacityControl/);
  assert.match(js, /clamp\(Number\(curtainOpacity\.value\), 10, 100\)/);
  assert.match(js, /set_window_opacity/);
  assert.match(js, /resetNativeWindowOpacity/);
  assert.match(js, /applyWindowOpacityForCurrentState/);
  assert.match(js, /transcriptDrawerOpen/);
  assert.match(js, /currentPartialTranscript/);
  assert.match(js, /native_transcript_preview/);
  assert.match(js, /handleNativeTranscriptPreview/);
  assert.match(js, /PARTIAL_TRANSCRIPT_COMMIT_IDLE_MS/);
  assert.match(js, /partial_idle/);
  assert.match(js, /promoteCurrentPartialTranscript/);
  assert.match(js, /preview_\$\{activeSessionId\}_\$\{transcriptIndex\}/);
  assert.match(js, /native\.promote_partial_transcript/);
  assert.match(js, /recognition_request_canceled/);
  assert.match(js, /記錄中/);
  assert.match(js, /TRANSCRIPT_STALL_MS/);
  assert.match(js, /startTranscriptStallMonitor/);
  assert.match(js, /native\.transcription_no_input/);
  assert.match(js, /目前只聽你的麥克風/);
  assert.match(js, /麥克風 \+ 系統音訊/);
  assert.match(js, /native_transcriber_health", \{\s*request: \{ source: requestedSource, sttProfileId: selectedLocalSttProfileId \}/);
  assert.match(js, /refreshNativeAudioReadiness\("startup"\)/);
  assert.match(js, /permissions\.native_audio_health/);
  assert.match(js, /setupAudioReadinessText\.textContent/);
  assert.match(js, /setupAudioPermissionsButton\?\.addEventListener\("click"/);
  assert.match(js, /openScreenRecordingSettings\("setup_audio_readiness"\)/);
  assert.match(js, /screenSystemAudioPreflight=false/);
  assert.match(js, /macOS 尚未把螢幕與系統錄音權限套用/);
  assert.match(js, /request_native_audio_permissions", \{\s*request: \{ source: requestedSource, sttProfileId: selectedLocalSttProfileId \}/);
  assert.match(js, /正在檢查音訊與權限/);
  assert.match(js, /會議無法開始/);
  assert.match(js, /isScreenRecordingPermissionMessage/);
  assert.match(js, /request_screen_recording_permission/);
  assert.doesNotMatch(js, /openScreenRecordingSettings\("screen_recording_required"\)/);
  assert.match(js, /openAudioPermissionsButton\?\.addEventListener\("click"/);
  assert.match(js, /renderTranscriptDrawer/);
  assert.match(js, /currentTranscriptLines/);
  assert.match(js, /transcriptSpeakerLabel/);
  assert.match(js, /event\.source === "mic"/);
  assert.match(js, /event\.source === "system"/);
  assert.match(js, /installPrepDictationListeners/);
  assert.match(js, /請先啟用 AI，才能使用語音輸入/);
  assert.match(js, /start_prep_dictation/);
  assert.match(js, /start_prep_dictation", \{ providerId: selectedTextProviderId\(\) \}/);
  assert.match(js, /stop_prep_dictation/);
  assert.match(js, /prep_dictation_text/);
  assert.match(js, /droppedContextChunks/);
  assert.match(js, /createBriefFromSetupContext/);
  assert.match(js, /installNativeDropListeners/);
  assert.match(js, /tauri:\/\/drag-drop/);
  assert.match(js, /read_dropped_context_files/);
  assert.match(js, /readBrowserDroppedFile/);
  assert.match(js, /isSupportedTextContextFileName/);
  assert.match(js, /droppedFileErrors/);
  assert.match(js, /contextDiagnostics/);
  assert.match(js, /if \(loadedFile\?\.text\)/);
  assert.match(js, /droppedFileNames\.push\(\.\.\.loaded\.map\(\(file\) => file\.name\)\)/);
  assert.match(js, /尚未加入會議背景/);
  assert.match(js, /updateAppState\("listening"\)/);
  assert.match(js, /enterReviewProcessing/);
  assert.match(js, /waitForReviewPaint/);
  assert.match(js, /const stoppingSessionId = activeSessionId/);
  assert.match(js, /finishNativeStopInBackground/);
  assert.match(js, /allowNewMeeting: false/);
  assert.match(js, /newMeetingButton\.disabled = !allowNewMeeting/);
  assert.match(js, /runAiSummary: false/);
  assert.match(js, /postMeetingAiSummaryStarted/);
  assert.match(js, /generateOAuthSummaryIfEnabled\(sessionId\)/);
  assert.match(js, /isCurrentReviewSession/);
  assert.match(js, /reviewScreen\.dataset\.reviewState = "processing"/);
  assert.match(js, /setDownloadActionsEnabled\(false\)/);
  assert.match(js, /renderProcessingDocument/);
  assert.match(js, /finalizeMeetingReview/);
  assert.match(js, /reviewScreen\.dataset\.reviewState = "ready"/);
  assert.match(js, /hasReviewContent/);
  assert.match(js, /renderNoReviewInput/);
  assert.match(js, /syncReviewDownloadButtons/);
  assert.match(js, /不會送出空內容給 AI/);
  assert.match(js, /沒有收到逐字稿，也沒有可整理的會前資料/);
  assert.match(js, /本機文件已整理完成/);
  assert.match(js, /AI 整理已更新/);
  assert.match(js, /已從系統列結束會議/);
  assert.match(js, /No speech detected/);
  assert.match(js, /沒有系統音訊權限/);
  assert.match(js, /系統音訊轉錄已停止/);
  assert.match(js, /語音轉錄已停止/);
  assert.match(js, /renderDecisionOverview/);
  assert.match(js, /renderSuggestionCard/);
  assert.match(js, /suggestion-title/);
  assert.match(js, /suggestion-move/);
  assert.match(js, /suggestion-watch/);
  assert.match(js, /coachingError/);
  assert.match(js, /AI 暫時無法產生提醒/);
  assert.match(js, /renderEvidenceLines/);
  assert.match(js, /labelCaptureSource/);
  assert.match(js, /labelLanguage/);
  assert.match(js, /formatAudioMonitorMessage/);
  assert.match(js, /prepSummaryInFlight/);
  assert.match(js, /updateAppState\("review"\)/);
  assert.match(js, /buildMeetingArtifact/);
  assert.match(js, /downloadMeetingArtifact/);
  assert.match(js, /downloadErrorLog/);
  assert.match(js, /export_app_error_logs/);
  assert.match(js, /logAppError/);
  assert.match(js, /browserErrorLogs/);
  assert.match(js, /buildAiSummaryDocument/);
  assert.match(js, /buildTranscriptDocument/);
  assert.match(js, /split\(\/\\n\|。\|；\|;\|\\\.\|！\|!\|？\|\\\?\//);
  assert.match(js, /renderAiSummaryMarkdown/);
  assert.match(js, /renderTranscriptText/);
  assert.match(js, /openPrintableDocument/);
  assert.match(js, /window\.open\("", "_blank"\)/);
  assert.match(js, /data-download-format/);
});
