import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("UI only exposes stage-appropriate controls", async () => {
  const [html, css, js, design] = await Promise.all([
    readFile(new URL("../src/ui/index.html", import.meta.url), "utf8"),
    readFile(new URL("../src/ui/styles.css", import.meta.url), "utf8"),
    readFile(new URL("../src/ui/app.mjs", import.meta.url), "utf8"),
    readFile(new URL("../DESIGN.md", import.meta.url), "utf8")
  ]);

  assert.match(design, /three-stage desktop utility/);
  assert.match(design, /Setup/);
  assert.match(design, /Listening/);
  assert.match(design, /Review/);
  assert.match(design, /Traditional Chinese/);
  assert.match(design, /AI suggestion must be dismissible/);

  assert.match(html, /body data-state="setup"/);
  assert.match(html, /setup-screen/);
  assert.match(html, /setupDropZone/);
  assert.match(html, /setupContext/);
  assert.match(html, /provider-settings/);
  assert.match(html, /textProviderName/);
  assert.match(html, /loginTextProvider/);
  assert.match(html, /enableOAuthProvider/);
  assert.match(html, /AI 狀態/);
  assert.match(html, /會前/);
  assert.match(html, /背景/);
  assert.match(html, /檔案/);
  assert.doesNotMatch(html, /檢查登入/);
  assert.match(html, /prepDictation/);
  assert.match(html, /droppedFileCount/);
  assert.match(html, /prepSummary/);
  assert.match(html, /AI 重點整理/);
  assert.match(html, /listening-curtain/);
  assert.match(html, /review-screen/);
  assert.match(html, /postMeetingSummary/);
  assert.match(html, /postMeetingTranscript/);
  assert.match(html, /data-download-format="summary-json"/);
  assert.match(html, /data-download-format="summary-markdown"/);
  assert.match(html, /data-download-format="summary-pdf"/);
  assert.match(html, /data-download-format="transcript-json"/);
  assert.match(html, /data-download-format="transcript-txt"/);
  assert.match(html, /data-download-format="transcript-pdf"/);
  assert.match(html, /downloadErrorLog/);
  assert.match(html, /錯誤紀錄 JSON/);
  assert.match(html, /AI 整理/);
  assert.match(html, /逐字稿/);
  assert.match(html, /curtainOpacity/);
  assert.match(html, /min="10"/);
  assert.match(html, /max="100"/);
  assert.match(html, /value="100"/);
  assert.match(html, /startListening[^>]+disabled/);
  assert.match(html, /transcript-drawer/);
  assert.match(html, /transcriptDrawerToggle/);
  assert.match(html, /transcriptPreview/);
  assert.match(html, /transcriptFull/);
  assert.match(html, /逐字稿/);
  assert.match(html, /目前沒有提醒/);
  assert.match(html, /0 句/);
  assert.match(html, /最近 3 句會顯示在這裡/);
  assert.match(html, /stopListening[^>]+>結束會議</);
  assert.doesNotMatch(html, /目前聽到的重點/);
  assert.doesNotMatch(html, /Popover 預覽/);
  assert.doesNotMatch(html, /手動逐字稿/);
  assert.doesNotMatch(html, /Native STT/);
  assert.doesNotMatch(html, />Pre-flight</i);
  assert.doesNotMatch(html, />Context</i);
  assert.doesNotMatch(html, />Files</i);
  assert.doesNotMatch(html, />AI Brief</i);
  assert.doesNotMatch(html, />Review</i);
  assert.doesNotMatch(html, />Document/);
  assert.doesNotMatch(html, />Export</i);

  assert.match(css, /body\[data-state="listening"\] \.setup-screen,[\s\S]*body\[data-state="review"\] \.listening-curtain\s*\{\s*display: none;/);
  assert.match(css, /body\[data-state="listening"\] \.listening-curtain,[\s\S]*body\[data-state="review"\] \.review-screen\s*\{\s*display: grid;/);
  assert.match(css, /\[hidden\]\s*\{\s*display: none !important;/);
  assert.match(css, /backdrop-filter: blur/);
  assert.match(css, /--curtain-alpha: 1/);
  assert.match(css, /--glass: rgba\(16, 18, 20, var\(--curtain-alpha\)\)/);
  assert.match(css, /body\[data-state="listening"\] \.shell\s*\{\s*background: transparent;/);
  assert.match(css, /\.transcript-drawer/);
  assert.match(css, /\.transcript-preview/);
  assert.match(css, /\.transcript-full/);
  assert.match(css, /\.transcript-line\.partial/);
  assert.match(css, /max-height: 34vh/);
  assert.match(css, /\.listening-status/);
  assert.match(css, /\.state-label::before/);
  assert.match(css, /\.prep-layout/);
  assert.match(css, /\.context-dropzone/);
  assert.match(css, /\.primary-export/);
  assert.match(css, /\.secondary-export/);
  assert.match(css, /\.evidence-disclosure/);

  assert.match(js, /initializeSetupState\(\)/);
  assert.match(js, /refreshPlatformShellPlan/);
  assert.match(js, /applyPlatformCaptureAvailability/);
  assert.match(js, /refreshTextProviderStatus/);
  assert.match(js, /scheduleTextProviderRefresh/);
  assert.match(js, /text_provider_status/);
  assert.match(js, /start_text_provider_login/);
  assert.match(js, /generate_ai_summary_oauth/);
  assert.match(js, /generate_prep_summary_oauth/);
  assert.match(js, /schedulePrepSummaryGeneration/);
  assert.match(js, /generatePrepSummary/);
  assert.match(js, /請先登入並啟用 AI/);
  assert.match(js, /extract_live_state_patch_oauth/);
  assert.match(js, /maybeRunLiveAiExtraction/);
  assert.match(js, /liveAiExtractionRunning/);
  assert.match(js, /Math\.max\(0, lastAiExtractionEventCount - 1\)/);
  assert.match(js, /lastAiExtractionEventCount/);
  assert.match(js, /AI 正在判斷是否需要提醒/);
  assert.match(js, /oauthAiEnabled/);
  assert.match(js, /canStartWithAi/);
  assert.match(js, /textProviderEnabled: canStartWithAi\(\)/);
  assert.match(js, /syncStartButtonAvailability/);
  assert.match(js, /請先啟用 AI/);
  assert.match(js, /ChatGPT 已啟用/);
  assert.match(js, /installOpacityControl/);
  assert.match(js, /clamp\(Number\(curtainOpacity\.value\), 10, 100\)/);
  assert.match(js, /set_window_opacity/);
  assert.match(js, /resetNativeWindowOpacity/);
  assert.match(js, /applyWindowOpacityForCurrentState/);
  assert.match(js, /transcriptDrawerOpen/);
  assert.match(js, /currentPartialTranscript/);
  assert.match(js, /native_transcript_preview/);
  assert.match(js, /記錄中/);
  assert.match(js, /renderTranscriptDrawer/);
  assert.match(js, /currentTranscriptLines/);
  assert.match(js, /transcriptSpeakerLabel/);
  assert.match(js, /event\.source === "mic"/);
  assert.match(js, /event\.source === "system"/);
  assert.match(js, /installPrepDictationListeners/);
  assert.match(js, /請先啟用 AI，才能使用語音輸入/);
  assert.match(js, /start_prep_dictation/);
  assert.match(js, /stop_prep_dictation/);
  assert.match(js, /prep_dictation_text/);
  assert.match(js, /droppedContextChunks/);
  assert.match(js, /createBriefFromSetupContext/);
  assert.match(js, /installNativeDropListeners/);
  assert.match(js, /tauri:\/\/drag-drop/);
  assert.match(js, /read_dropped_context_files/);
  assert.match(js, /readBrowserDroppedFile/);
  assert.match(js, /updateAppState\("listening"\)/);
  assert.match(js, /finalizeMeetingReview/);
  assert.match(js, /已從系統列結束會議/);
  assert.match(js, /renderDecisionOverview/);
  assert.match(js, /renderSuggestionCard/);
  assert.match(js, /renderEvidenceLines/);
  assert.match(js, /labelCaptureSource/);
  assert.match(js, /labelLanguage/);
  assert.match(js, /formatAudioMonitorMessage/);
  assert.match(js, /prepSummaryInFlight/);
  assert.match(js, /updateAppState\("review"\)/);
  assert.match(js, /buildMeetingArtifact/);
  assert.match(js, /downloadMeetingArtifact/);
  assert.match(js, /downloadErrorLog/);
  assert.match(js, /export_app_error_logs/);
  assert.match(js, /logAppError/);
  assert.match(js, /browserErrorLogs/);
  assert.match(js, /buildAiSummaryDocument/);
  assert.match(js, /buildTranscriptDocument/);
  assert.match(js, /renderAiSummaryMarkdown/);
  assert.match(js, /renderTranscriptText/);
  assert.match(js, /openPrintableDocument/);
  assert.match(js, /window\.open\("", "_blank"\)/);
  assert.match(js, /data-download-format/);
});
